### ISSUE TITLE
相对于推理后端的可变长文本的推理BUG

### ISSUE THREAD

**Issue by Huiyicc** [second-state/gpt_sovits_rs#2]
# 说明
使用例如:`今天是2021年11月23日,天气晴,气温32°C.`这种会被代码后端清理/处理的文本可能在清理之后长度会被改变,这是在移植c++版本之后进行极端单元测试时偶然发现的bug

### 报错如下
![1732383296964](https://github.com/user-attachments/assets/f79b3b1d-89ee-4f16-b9c7-e551d6ad2256)

### 错误原因
![image](https://github.com/user-attachments/assets/7d7ef341-4875-45dd-a009-c98d6c2f66bb)

### 修改方法
![image](https://github.com/user-attachments/assets/39874027-2e1d-49d5-bb12-8919f8d399b7)

![1732383169484](https://github.com/user-attachments/assets/8f1f814c-f9a5-42c5-a41d-31c4904d0dc5)

最后经过测试本项目也存在同样的问题,应该也是相同的错误逻辑,但是本人对rust熟悉程度仅限于勉强能看懂的地步,所以就仅报告以下issues 不发 Pull requests 了🤯
![1732383259347](https://github.com/user-attachments/assets/4312497f-e2f5-46fc-8469-79f1f21007c5)

**Comment by L-jasmine** [comment]
感谢issues，但是我在 main 上并没有复现这个bug。你本地的 repo 是最新版本吗？

**Comment by Huiyicc** [comment]
> 感谢issues，但是我在 main 上并没有复现这个bug。你本地的 repo 是最新版本吗？

好的，应该是我没更新的问题😂，main上的最新提交确实是正常的
